name: irop_gnn_risk_app
channels:
  - snowflake
dependencies:
  - python=3.11
  - streamlit=1.35.0
  - snowflake-snowpark-python
  - snowflake-ml-python
  - pandas
  - numpy
  - plotly
  - altair
  - pydeck
